---
abstract: 'inofficial interface to the efa.vrr.de German itinerary service'
author:
  - 'Copyright (C) 2009-2011 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>'
build_requires:
  Test::Compile: 0
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Travel-Routing-DE-VRR
provides:
  Travel::Routing::DE::VRR:
    file: lib/Travel/Routing/DE/VRR.pm
    version: 1.04
  Travel::Routing::DE::VRR::Route:
    file: lib/Travel/Routing/DE/VRR/Route.pm
    version: 1.04
  Travel::Routing::DE::VRR::Route::Part:
    file: lib/Travel/Routing/DE/VRR/Route/Part.pm
    version: 1.04
requires:
  Class::Accessor: 0
  Exception::Class: 0
  Getopt::Long: 0
  WWW::Mechanize: 0
  XML::LibXML: 0
  perl: v5.10.0
version: 1.04
